### ISSUE TITLE
[1.20.1, v1.0.3] Logspam issue

### ISSUE THREAD

**Issue by Gronglegrowth** [ACCBDD/complicated_bees#10]
I added this to a 1.20.1 pack to see what all it has, and how it plays. With v1.0.3, the following line was getting spammed in the log repeatedly, producing a _very_ large log by the time I noticed:
`[Server thread/ERROR] [com.accbdd.complicated_bees.ComplicatedBees/]: Centrifuge recipe tried to use getResultItem! Use getOutputs instead`
I assume that's a mistake with the recipes somehow?

**Comment by ACCBDD** [comment]
This is a known issue with either EMI or REI - which one are you using?

**Comment by ACCBDD** [comment]
tested and resolved in v1.0.4
