### ISSUE TITLE
instance doesnt start

### ISSUE THREAD

**Issue by koostcrashed** [ACCBDD/complicated_bees#13]
**Describe the bug**
Instance crashes and shows
java.lang.NoSuchMethodException:
com.accbdd.complicated_bees.ComplicatedBees.<init>()

(new one for me, so im not sure what im looking for)
**To Reproduce**
start the instance.
(im in the process of going through the mod list, but i haven't found out which one is causing the conflict just yet)
(big list, sorry)

**Expected behavior**
load the title screen and load a world

**Screenshots**
![image](https://github.com/user-attachments/assets/cc98d0a8-5de6-4c40-b209-a66db0a7b32f)

**Mod Version**
1.20.1-1.0.5

**Logs**
https://pastebin.com/yXTEVcmE

**Comment by ACCBDD** [comment]
This is a semi-known bug - can you try updating your Forge version to 47.3.10 or 47.3.11?

**Comment by koostcrashed** [comment]
Yup that fixed it.
Anything i should check?

**Comment by ACCBDD** [comment]
Nope! That's all I needed to know - you should be using the latest version regardless, but I'll include a patch for the next minor version to fix this for the latest recommended version (47.3.0)
