### ISSUE TITLE
Game crashing when trying to access jei.MutationRecipeCategory

### ISSUE THREAD

**Issue by jamesjimmy88** [ACCBDD/complicated_bees#15]
Nothing much to say here, just launch the game and left click on any non-basic bee to try to open the mutation recipe for them - the recipe screen doesn't show up and the game crashes. Same thing happens if you click on the _mutations_ tab in JEI. Here's a [crash log](https://pastebin.com/01q3mHsi).
Tested on forge 47.3.11 - mod list:
- complicated_bees-1.20.1-1.0.5
- jei-1.20.1-forge-15.20.0.104
- Patchouli-1.21-87-NEOFORGE

**Comment by ACCBDD** [comment]
thanks for submitting a report! I think i know what the issue is - i'll push a hotfix out in ~24 hours.
