### ISSUE TITLE
Nests only spawn in vanilla biomes

### ISSUE THREAD

**Issue by jamesjimmy88** [ACCBDD/complicated_bees#17]
As per title. Looking at the mod's datapack under forge/biome_modifier it looks like it's because the biomes were handpicked. It might be an easy fix with biome tags, but I'm not knowledgeable enough to say for sure.
Tested on complicated_bees-1.20.1-1.0.6 on forge 47.3.11

**Comment by ACCBDD** [comment]
this is a semi-easy fix if I wanted to use tags, but the issue with tags is that there are some situations where nests would spawn in biomes that technically can't support the nests. this will be something i'll work on when i have time - a datapack that adds nests to terralith, bop, and byg biomes.

**Comment by ACCBDD** [comment]
this has been added in 1.1.0
