### ISSUE TITLE
Significant fps lag when looking at many bees through emi

### ISSUE THREAD

**Issue by Pers-Pluto** [ACCBDD/complicated_bees#18]
To reproduce: Forge 47.3.0, Complicated Bees 1.0.6, EMI 1.1.16, JEI 15.20.0.104 on MC 1.20.1

Looking at ~150 bees (All the bees in the mod, typed in `@complicated` on EMI ), fps decreased from ~120 to ~15 w/o any other mods; with performance increasing mods, it decreased from ~200 to ~30.

Are the bees rendered in a particularly inefficient way, such as being re-rendered every second or tick?

**Comment by ACCBDD** [comment]
this now lags only in the inventory - looking into further optimizations
